#pragma once

#define FASTFETCH_PROJECT_NAME "fastfetch"
#define FASTFETCH_PROJECT_VERSION "2.62.1"
#define FASTFETCH_PROJECT_VERSION_MAJOR 2
#define FASTFETCH_PROJECT_VERSION_MINOR 62
#define FASTFETCH_PROJECT_VERSION_PATCH 1
#define FASTFETCH_PROJECT_VERSION_GIT "CLeonOS"
#define FASTFETCH_PROJECT_VERSION_TWEAK ""
#define FASTFETCH_PROJECT_VERSION_TWEAK_NUM 0
#define FASTFETCH_PROJECT_CMAKE_BUILD_TYPE "Release"
#define FASTFETCH_PROJECT_HOMEPAGE_URL "https://github.com/fastfetch-cli/fastfetch"
#define FASTFETCH_PROJECT_DESCRIPTION "A maintained, feature-rich and performance oriented neofetch like system information tool"
#define FASTFETCH_PROJECT_LICENSE "MIT"

#define FASTFETCH_TARGET_DIR_ROOT "/"
#define FASTFETCH_TARGET_DIR_USR "/system"
#define FASTFETCH_TARGET_DIR_HOME "/home"
#define FASTFETCH_TARGET_DIR_ETC "/etc"
#define FASTFETCH_TARGET_DIR_INSTALL_SYSCONF "/etc"

#define FASTFETCH_LOGO_MAX_NAMES 8
#define FASTFETCH_LOGO_MAX_COLORS 9

#define FF_WIN81_COMPAT 0
#define FF_APPLE_MEMSIZE_USABLE 0
#define FF_USE_SYSTEM_YYJSON 0
