timeout: 3
verbose: yes

/CLeonOS
protocol: limine
kernel_path: boot():/kernel.elf

/CLeonOS Rescue Mode
protocol: limine
kernel_path: boot():/kernel.elf
kernel_cmdline: clks.rescue=1 clks.nosplash=1
