timeout: 3
verbose: yes
graphics: yes
interface_branding: CLeonOS Boot Manager
interface_branding_colour: 6
interface_help_colour: 3
term_background: 0000182A
term_foreground: C8D7E1
term_background_bright: 1E3A4D
term_foreground_bright: F8F8F2
term_palette: 00182A;B85C5C;69A86F;C5A85A;4D89C8;9A78B8;4FB8B0;C8D7E1
term_palette_bright: 14334A;E07171;8AD08F;E5C76B;72AEEF;C19BE0;75E0D8;F8F8F2
term_margin: 48
term_margin_gradient: 4

/Try CLeonOS

//CLeonOS English
protocol: limine
kernel_path: boot():/boot/clks_kernel.elf
kernel_cmdline: clks.locale=en_US
module_path: boot():/boot/cleonos_ramdisk.tar

//CLeonOS Chinese
protocol: limine
kernel_path: boot():/boot/clks_kernel.elf
kernel_cmdline: clks.locale=zh_CN
module_path: boot():/boot/cleonos_ramdisk.tar

/Verbose Boot
protocol: limine
kernel_path: boot():/boot/clks_kernel.elf
kernel_cmdline: clks.loglevel=debug
module_path: boot():/boot/cleonos_ramdisk.tar

/Quiet Boot
protocol: limine
kernel_path: boot():/boot/clks_kernel.elf
kernel_cmdline: clks.loglevel=quiet
module_path: boot():/boot/cleonos_ramdisk.tar

/Install to Disk
protocol: limine
kernel_path: boot():/boot/clks_kernel.elf
kernel_cmdline: clks.installer=install
module_path: boot():/boot/cleonos_ramdisk.tar

/Repair Disk System
protocol: limine
kernel_path: boot():/boot/clks_kernel.elf
kernel_cmdline: clks.installer=repair
module_path: boot():/boot/cleonos_ramdisk.tar

/Update Kernel
protocol: limine
kernel_path: boot():/boot/clks_kernel.elf
kernel_cmdline: clks.installer=update-kernel
module_path: boot():/boot/cleonos_ramdisk.tar

/Verify Installation
protocol: limine
kernel_path: boot():/boot/clks_kernel.elf
kernel_cmdline: clks.installer=verify
module_path: boot():/boot/cleonos_ramdisk.tar
