#!/usr/bin/env python3
from __future__ import annotations

from pathlib import Path
import re


ROOT = Path(__file__).resolve().parent.parent
CONFIG_DIR = ROOT / "configs" / "menuconfig"
OUT_DIR = ROOT / "build" / "bdt-menuconfig"
CLKS_CONFIG = CONFIG_DIR / "config.clks.bdt"
CLKS_HEADER = OUT_DIR / "clks_config.h"


def read_bdt(path: Path) -> dict[str, str]:
    values: dict[str, str] = {}
    if not path.exists():
        return values
    for raw in path.read_text(encoding="utf-8").splitlines():
        line = raw.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        values[key.strip()] = value.strip().strip('"').strip("'")
    return values


def enabled(value: str | None) -> int:
    if value is None:
        return 0
    return 1 if value.strip().upper() in {"1", "Y", "M", "ON", "TRUE", "YES"} else 0


def macro_for_key(key: str) -> str | None:
    prefix = "CLEONOS_CLKS_ENABLE_"
    if not key.startswith(prefix) or key.endswith("_IS_ENABLED"):
        return None
    tail = key[len(prefix) :]
    tail = re.sub(r"[^A-Z0-9]+", "_", tail.upper()).strip("_")
    if not tail:
        return None
    return f"CLKS_CFG_{tail}"


def main() -> int:
    values = read_bdt(CLKS_CONFIG)
    OUT_DIR.mkdir(parents=True, exist_ok=True)

    lines = [
        "/* Auto-generated by scripts/bdt_gen_menuconfig.py. */",
        "#ifndef BDT_GENERATED_CLKS_CONFIG_H",
        "#define BDT_GENERATED_CLKS_CONFIG_H",
        "#ifndef CLKS_ARCH_X86_64",
        "#define CLKS_ARCH_X86_64 1",
        "#endif",
    ]

    for key in sorted(values):
        macro = macro_for_key(key)
        if not macro:
            continue
        is_enabled_key = f"{key}_IS_ENABLED"
        value = values.get(is_enabled_key, values.get(key))
        lines.append(f"#ifndef {macro}")
        lines.append(f"#define {macro} {enabled(value)}")
        lines.append("#endif")

    lines.append("#endif")
    CLKS_HEADER.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"[bdt-menuconfig] wrote {CLKS_HEADER}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
