#!/usr/bin/env python3
from __future__ import annotations

import argparse
import os
import re
import shutil
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
CONFIG_DIR = ROOT / "configs" / "menuconfig"
KCONFIG = CONFIG_DIR / "Kconfig"
DOTCONFIG = CONFIG_DIR / ".config"
BDT_CONFIG = CONFIG_DIR / "config.clks.bdt"
OUT_DIR = ROOT / "build" / "bdt-menuconfig"
HEADER = OUT_DIR / "clks_config.h"
ENV_BASE = os.environ.copy()
ENV_BASE["KCONFIG_CONFIG"] = str(DOTCONFIG)

TRI_VALUES = {"y": 2, "m": 1, "n": 0}
MINIMAL_DISABLE = {
    "AUDIO",
    "MOUSE",
    "DESKTOP",
    "WM_MULTI_RECT_DAMAGE",
    "WM_LAYER_CACHE",
    "WM_FRAME_PACING",
    "WM_STATS_OVERLAY",
    "WM_INPUT_DISPATCH",
    "WM_REAP_DEAD_OWNERS",
    "DRIVER_MANAGER",
    "EXTERNAL_PSF",
    "EXTERNAL_TTY_FONT",
    "KLOGD_TASK",
    "KWORKER_TASK",
    "BOOT_VIDEO_LOG",
    "PMM_STATS_LOG",
    "HEAP_STATS_LOG",
    "FS_ROOT_LOG",
    "SYSCALL_TICK_QUERY",
    "TTY_READY_LOG",
    "IDLE_DEBUG_LOG",
    "EXEC_CONTEXT_SWITCH_LOG",
    "SCHED_TASK_COUNT_LOG",
}
MINIMAL_ENABLE = {
    "KEYBOARD",
    "USRD_TASK",
    "USER_SPACE_ENTER",
    "USER_SPACE_ENTER_CONFIG",
    "USER_SPACE_ENTER_STRICT_PANIC",
    "HEAP_SELFTEST",
    "SYSTEM_DIR_CHECK",
    "PROCFS",
    "EXEC_SERIAL_LOG",
    "KBD_TTY_SWITCH_HOTKEY",
    "KBD_CTRL_SHORTCUTS",
    "KBD_FORCE_STOP_HOTKEY",
    "INTERRUPT_READY_LOG",
}
DEV_FORCE = {
    "USER_SPACE_ENTER": "y",
    "USER_SPACE_ENTER_CONFIG": "y",
    "USER_SPACE_ENTER_STRICT_PANIC": "y",
    "EXEC_SERIAL_LOG": "y",
    "EXEC_CONTEXT_SWITCH_LOG": "n",
    "PROCFS": "y",
    "IDLE_DEBUG_LOG": "y",
}
ALIASES = {
    "EXTERNAL_PSF": "EXTERNAL_TTY_FONT",
}


def run(cmd: list[str], *, env: dict[str, str] | None = None, check: bool = True) -> subprocess.CompletedProcess[str]:
    return subprocess.run(cmd, cwd=str(ROOT), env=env, text=True, check=check)


def which(names: list[str]) -> str | None:
    for name in names:
        found = shutil.which(name)
        if found:
            return found
    return None


def find_conf() -> str | None:
    return which(["kconfig-conf", "conf"])


def find_mconf() -> str | None:
    return which(["kconfig-mconf", "mconf", "menuconfig"])


def ensure_kconfig() -> None:
    if not KCONFIG.is_file():
        raise SystemExit(f"kconfig: missing {KCONFIG}")


def parse_symbols_from_kconfig() -> dict[str, str]:
    symbols: dict[str, str] = {}
    last: str | None = None
    for raw in KCONFIG.read_text(encoding="utf-8").splitlines():
        line = raw.strip()
        if line.startswith("config "):
            last = line.split(None, 1)[1].strip()
            symbols[last] = "bool"
        elif last and (line.startswith("bool") or line.startswith("tristate")):
            symbols[last] = line.split(None, 1)[0]
    return symbols


def parse_config(path: Path = DOTCONFIG) -> dict[str, str]:
    values: dict[str, str] = {}
    if not path.exists():
        return values
    for raw in path.read_text(encoding="utf-8").splitlines():
        line = raw.strip()
        if not line:
            continue
        if line.startswith("# CONFIG_") and line.endswith(" is not set"):
            name = line[len("# CONFIG_") : -len(" is not set")]
            values[name] = "n"
        elif line.startswith("CONFIG_") and "=" in line:
            name, value = line.split("=", 1)
            values[name[len("CONFIG_") :]] = value.strip().strip('"')
    return values


def write_config(values: dict[str, str], symbols: dict[str, str]) -> None:
    CONFIG_DIR.mkdir(parents=True, exist_ok=True)
    lines = ["# Auto-generated by scripts/kconfig_sync.py", ""]
    for name in sorted(symbols):
        value = values.get(name, "n").lower()
        if value in {"y", "m"}:
            lines.append(f"CONFIG_{name}={value}")
        else:
            lines.append(f"# CONFIG_{name} is not set")
    DOTCONFIG.write_text("\n".join(lines) + "\n", encoding="utf-8")


def normalize_value(value: str, kind: str) -> str:
    raw = value.strip().lower()
    if raw in {"1", "y", "yes", "true", "on"}:
        return "y"
    if raw in {"m", "module"} and kind == "tristate":
        return "m"
    if raw in {"0", "n", "no", "false", "off"}:
        return "n"
    raise SystemExit(f"kconfig: invalid value {value!r} for {kind}")


def apply_preset(values: dict[str, str], symbols: dict[str, str], preset: str | None) -> None:
    if not preset:
        return
    name = preset.strip().lower()
    if name == "full":
        for sym in symbols:
            values[sym] = "y"
        return
    if name == "dev":
        for sym in symbols:
            values[sym] = "y"
        for sym, val in DEV_FORCE.items():
            if sym in symbols:
                values[sym] = val
        return
    if name == "minimal":
        for sym in symbols:
            values[sym] = "y"
        for sym in MINIMAL_DISABLE:
            if sym in symbols:
                values[sym] = "n"
        for sym in MINIMAL_ENABLE:
            if sym in symbols:
                values[sym] = "y"
        return
    raise SystemExit(f"kconfig: unknown preset: {preset}")


def apply_overrides(values: dict[str, str], symbols: dict[str, str], pairs: list[str]) -> None:
    for pair in pairs:
        if "=" not in pair:
            raise SystemExit(f"kconfig: invalid --set entry: {pair!r}, expected KEY=Y|M|N")
        key, raw_value = pair.split("=", 1)
        key = key.strip()
        if key.startswith("CONFIG_"):
            key = key[len("CONFIG_") :]
        if key.startswith("CLEONOS_CLKS_ENABLE_"):
            key = key[len("CLEONOS_CLKS_ENABLE_") :]
        key = key.strip().upper()
        if key not in symbols:
            raise SystemExit(f"kconfig: unknown symbol: {key}")
        values[key] = normalize_value(raw_value, symbols[key])


def olddefconfig() -> None:
    conf = find_conf()
    if conf:
        run([conf, "--olddefconfig", str(KCONFIG)], env=ENV_BASE)
        return
    symbols = parse_symbols_from_kconfig()
    values = parse_config()
    for sym in symbols:
        values.setdefault(sym, "n")
    write_config(values, symbols)


def defconfig(preset: str | None = None, overrides: list[str] | None = None, defaults: bool = False) -> None:
    symbols = parse_symbols_from_kconfig()
    values = {} if defaults else parse_config()
    if defaults or not values:
        for sym in symbols:
            values[sym] = "n"
    apply_preset(values, symbols, preset or "full")
    apply_overrides(values, symbols, overrides or [])
    write_config(values, symbols)
    olddefconfig()


def menuconfig() -> None:
    mconf = find_mconf()
    if not mconf:
        raise SystemExit("kconfig: menuconfig frontend not found. Install kconfig-frontends or kconfig-frontends-nox.")
    if not DOTCONFIG.exists():
        defconfig("full")
    run([mconf, str(KCONFIG)], env=ENV_BASE)


def macro_for_symbol(symbol: str) -> str:
    tail = ALIASES.get(symbol, symbol)
    tail = re.sub(r"[^A-Z0-9]+", "_", tail.upper()).strip("_")
    return f"CLKS_CFG_{tail}"


def enabled(value: str | None) -> int:
    return 1 if value and value.lower() in {"y", "m"} else 0


def export_outputs() -> None:
    if not DOTCONFIG.exists():
        defconfig("full")
    values = parse_config()
    symbols = parse_symbols_from_kconfig()
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    CONFIG_DIR.mkdir(parents=True, exist_ok=True)

    bdt_lines = [
        "# Auto-generated by scripts/kconfig_sync.py",
        "# Do not edit manually unless you know what you are doing.",
        "CLEONOS_MENUCONFIG_CLKS_LOADED = true",
    ]
    header_lines = [
        "/* Auto-generated by scripts/kconfig_sync.py. */",
        "#ifndef BDT_GENERATED_CLKS_CONFIG_H",
        "#define BDT_GENERATED_CLKS_CONFIG_H",
        "#ifndef CLKS_ARCH_X86_64",
        "#define CLKS_ARCH_X86_64 1",
        "#endif",
    ]

    exported_macros: set[str] = set()
    for sym in sorted(symbols):
        value = values.get(sym, "n").lower()
        legacy = f"CLEONOS_CLKS_ENABLE_{sym}"
        if symbols[sym] == "tristate":
            bdt_val = value.upper() if value in {"y", "m"} else "N"
            bdt_lines.append(f"{legacy} = {bdt_val}")
            bdt_lines.append(f"{legacy}_IS_ENABLED = {'true' if enabled(value) else 'false'}")
        else:
            bdt_lines.append(f"{legacy} = {'true' if enabled(value) else 'false'}")
        macro = macro_for_symbol(sym)
        exported_macros.add(macro)
        header_lines.append(f"#ifndef {macro}")
        header_lines.append(f"#define {macro} {enabled(value)}")
        header_lines.append("#endif")

    for old_sym, new_sym in ALIASES.items():
        if old_sym in symbols:
            old_macro = f"CLKS_CFG_{old_sym}"
            new_macro = f"CLKS_CFG_{new_sym}"
            if old_macro not in exported_macros:
                header_lines.append(f"#ifndef {old_macro}")
                header_lines.append(f"#define {old_macro} {new_macro}")
                header_lines.append("#endif")

    header_lines.append("#endif")
    BDT_CONFIG.write_text("\n".join(bdt_lines) + "\n", encoding="utf-8")
    HEADER.write_text("\n".join(header_lines) + "\n", encoding="utf-8")
    print(f"[kconfig] wrote {DOTCONFIG}")
    print(f"[kconfig] wrote {BDT_CONFIG}")
    print(f"[kconfig] wrote {HEADER}")


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(description="CLeonOS Kconfig helper")
    sub = parser.add_subparsers(dest="cmd", required=True)
    p_def = sub.add_parser("defconfig")
    p_def.add_argument("--preset", choices=["full", "minimal", "dev"], default="full")
    p_def.add_argument("--defaults", action="store_true")
    p_def.add_argument("--set", action="append", default=[])
    sub.add_parser("olddefconfig")
    sub.add_parser("menuconfig")
    sub.add_parser("export")
    args = parser.parse_args(argv)
    ensure_kconfig()
    if args.cmd == "defconfig":
        defconfig(args.preset, args.set, defaults=True if args.defaults else False)
        export_outputs()
    elif args.cmd == "olddefconfig":
        olddefconfig()
        export_outputs()
    elif args.cmd == "menuconfig":
        menuconfig()
        export_outputs()
    elif args.cmd == "export":
        export_outputs()
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
